version: "3.4"

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - sandbox_database:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - sandbox_statics:/usr/src/staticfiles
      - ./src:/usr/src/app
    env_file:
      - ./.env.dev

  ngnix:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - sandbox_statics:/usr/src/staticfiles
    depends_on:
      - web

volumes:
  sandbox_database:
  sandbox_statics: